In [7]:
import numpy as np

# Step 1: Generate a random 3x4 matrix
np.random.seed(42)  # Ensures reproducibility for testing
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Generates random integers in the range [1, 20]

# Extract coefficient matrix (A) and right-hand side vector (b)
A = matrix_3x4[:, :3]
b = matrix_3x4[:, 3]

# Display the generated matrix and its components
print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)




Generated 3x4 Matrix:
[[ 7 20 15 11]
 [ 8  7 19 11]
 [11  4  8  3]]

Coefficient Matrix (A):
[[ 7 20 15]
 [ 8  7 19]
 [11  4  8]]

Right-hand Side Vector (b):
[11 11  3]


In [8]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_inverse = np.dot(A_inv, b)  # Compute solution x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_inverse)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")




Solution using Matrix Inverse Method:
[-0.23741007  0.17122302  0.61582734]


In [9]:
# Solve using Gaussian Elimination
try:
    x_gaussian = np.linalg.solve(A, b)  # Directly solve Ax = b
    print("\nSolution using Gaussian Elimination (NumPy):")
    print(x_gaussian)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular or not square.")




Solution using Gaussian Elimination (NumPy):
[-0.23741007  0.17122302  0.61582734]


In [10]:
# Verify the solution
if 'x_gaussian' in locals():
    b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
    print("\nVerification (Ax = b):")
    print(b_check)


Verification (Ax = b):
[11. 11.  3.]
